# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = "CentOS_6.3"

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", "4000"]
  end

  config.vm.synced_folder '/Users/scalvert/code', '/home/vagrant/code'
  config.vm.synced_folder '/Users/scalvert/env', '/home/vagrant/env'

  config.vm.provision 'chef_solo' do |chef|
    chef.cookbooks_path = ['tripit_cookbooks', 'cookbooks']
    chef.add_recipe 'yum'
    chef.add_recipe 'yum::epel'
    chef.add_recipe 'python'
    chef.add_recipe 'python::pip'
    chef.add_recipe 'datamapper'
  
    # You may also specify custom JSON attributes:
    chef.json = {}
  end
end
